[workspace]
members = [
    "filecoindot",
    "filecoindot-io",
    "filecoindot-proofs",
    "filecoindot-rpc",
    # node-example
    "substrate-node-example/node",
    "substrate-node-example/runtime",
    "filecoindot-cli",
]
