name: Check Licence

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  check-licence:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: Install addlicense
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          go get -v -u github.com/google/addlicense
      - name: Check license
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          addlicense -check -c "ChainSafe Systems" -f ./scripts/header.txt -y 2021 $(find $PWD -type f -name '*.rs')
