name: Release

on:
  push:
    branches:
      - 'master'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: tag
    if: ${{ needs.tag.outputs.tag != ''}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 16
          always-auth: true
          registry-url: 'https://registry.npmjs.org'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Build and Publish
        run: cd js && yarn && yarn run publish
